#!/bin/sh /etc/rc.common

START=91
STOP=91

USE_PROCD=1

start_service() {
	local wan_dev="eth0.2"
        local wan_exist
        local i=0
	
	while [[ $i -lt 10 ]]
        do
                cat /proc/net/dev | grep $wan_dev 2> /dev/null

                if [[ "$?" -ne 0 ]]
                then
                        echo "===>not found wan device $i" > /var/log/hwnat_insmod_info
                        i=$(($i+1))
                        sleep 3
                else
                        echo "===>found wan device $i" > /var/log/hwnat_insmod_info
			insmod /lib/modules/ralink/hw_nat.ko
        		mknod /dev/hwnat0 c 220 0
                        break
                fi
        done
}

stop_service() {
	rmmod hw_nat.ko
}


